### register user
POST http://localhost:3600/api/register
Content-Type: application/json

{
    "firstName": "Ghulam",
    "lastName": "Karimi",
    "email": "karimiamirhossein12@gmail.com",
    "password": "Hossein.123?",
    "confirmPassword": "Hossein.123?",
    "isAdmin": false
}

### get all users
GET http://localhost:3600/api/user


### verify user
GET  http://localhost:3600/api/verify_token/ac68ddb890fdd3c6181127979e87bcdd
 

### login user
POST http://localhost:3600/api/login
Content-Type: application/json

{
    "email": "karimiamirhossein12@gmail.com",
    "password": "Hossein.123?"
}

### logout user
DELETE  http://localhost:3600/api/logout/458c049695de7a675caa2ebc165238df



 